version: '2'

services:
  gitbucket:
    container_name: gbj-gitbucket
    image: shomatan/gitbucket
    ports:
      - "8080:8080"
      - "29418:29418"
    volumes:
      - ./volumes/gitbucket/repositories:/gitbucket/repositories
      - ./volumes/gitbucket/data:/gitbucket/data
    restart: always

  db:
    container_name: gbj-postgres
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: gitbucket
      POSTGRES_USER: gitbucket
      POSTGRES_PASSWORD: gitbucket
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  jenkins:
    container_name: gbj-jenkins
    image: jenkins:2.60.2-alpine
    ports:
      - "8081:8080"
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
    restart: always
